# DOING POC. WILL REVERT AFTER THAT
language: java
jdk:
  - oraclejdk8
  
# whitelist
branches:
  only:
    - master
    
deploy:
  provider: "codedeploy"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "shadowpact"
  skip_cleanup: "true"
  bundle_type: "jar"
  key: "*.jar"
  debug: "true"
  application: "node-app"
  region: "us-west-2"
  deployment_group: "springappGroup"
  local-dir: "build/libs"
  on:
    branch: "master"
