addons:
 artifacts: 
  paths:
   - $(git ls-files -o | tr "\n" ":")
  debug: true
env:
 global:
  - "ARTIFACTS_AWS_REGION=eu-west-1"
  - "ARTIFACTS_S3_BUCKET=shadowpact"
  - secure: "pL5T1HrW4dgIfZ/C+uP17saM1X7fnwwUGPvQcwUnAvdbd/h8Hn6GX8OraxzVKZ/etG2ySEY4U3KLMCdUxW2w5nIWtclRb3WYmbJcH8KE9dAXgBW2kBM1BuzJZvZzE/tbbckSSKzjNtqlF1r5xIncgWox9tm2rRcGkb9rsCDo5RHrKpNd+No/AXaqsIZUOhdSCYMzm3yx331e2Z/gVbQ34fy1o4jZ4u/uU33jrGOUje2i0XtFfzomeoQmAVU6ra/QDNMFpLna3NbjSDyMkPO0wdKT2CtWbOG6psoSMOzXTztzbxUaJdfAZqaY5CQFlWkTB5nztHcxqkPglKF/Hft9KIHSVvWgIs48SUxzHIp12fAWsABEzhZeX85qoNnHdZZxWBeGO1gl42dAF1+2dW5JB+HLohVEviv9vyVodTxyDko8wJxkuB//mNytyQmysycIBUOzQYhxp0p5dt9ADF9AzvNtAYLVu5VxxqX85+uG48q+kDkQzuvXsvFmAevmGdCGjYqrHI5S9/Vi1ir5VINZEi2EzbMTvDMbUJ+XjSc+UcXce5qzfKZwL14Z5c+JGkABZy56cdkaJeIvlY0SyGcGjxODARU5avdxOtBW9vt/VQjEdJPCJtFPd8SyMqdWxIv5t1oSKDD8QCGpVF56B4u/JXF1pOpz5UEMFR4fbkFfvMg="
  - secure: "FCuBn4EOgGET4iLP0rxsMI3QP6MHtro0c0Qr08L47xk4I+knozE+BaMsZvFx5EJ7smbVyTmSSWfr0zlObzRacIx+OIARGwtWZSXxfLTvhkSEHo/wVKrfIwR+eAnhBxvM0b1OO3nDbnpSz6gcp3KcVVzh/WcsAxzVAwSH2VqIO3Po/ITk6Zhf/MppggvHBuL4lLSqGK7LbIWA8A4r1aKKMiTXTp2hXPMd7CXqKQP3tyIj5eo6uabEpZsZMlLCPQzDRfTL2bTuSRuP4OwxnZXLgvI+Ob+NqvLMd3T0Koh6jlXbuKqDU9K8CvIAFHrHs1O+L9Cjj56cv3c6fK+3Lo1ZZydhxWsE+mIibaIdvdl3Xdb4GelDKJQmCRUITwOKNVXGjhjrIR7FLbnY3Z0OKkgN00wK+1qPMg2tZ8SFWXg+D0yd+cqe5xrzcjDo7QBVK8Hx2FlxSUQMGM7u96m+fdqrvQ6KuyvZYOI4ykyVTpxt0ujPhmtIpEH0HChEup0FpU6dT9ehfVUtLzvBDOx9PCkl0Vfn6PrFjYWwWRL4LNsUUw+djPc2NCASmnbqEoh5m83Sk9/dJn1Or6UPYLilrCHg5i7phElxoDs1nnrAZXqz4fSio8wdfWN80/EwmkAKEa9EEtLBdD8iSxgyrD/y+IcJV1BwgFc31Y5zZcv8Nxg6Up8="

language: java
jdk:
  - oraclejdk8
before_script:
  - "gem install travis-artifacts"
after_failure: # this will of course run only on failure
  - "travis-artifacts upload --path debug/debug.log"
after_success: # and this only on success
  - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
  
