language: java
jdk:
  - oraclejdk8
  
# whitelist
branches:
  only:
    - master
    
deploy:
  provider: "codedeploy"
  access_key_id: "XgUk/uDroFfForAVPaUPPNhwZn3mXpC1iKX9HcrYgnBYlq3N6Y8mfu+bAhQ9/9NhKcJI5l5CsbN7C4X0kHL6QdziQllGpl+BnmF+vT1yP2xz15wBv2RDqEWyi5GB8LtHFHzgsM62FcHqzwBUVZ5+cONHOCeQB+/flrLdFvHPQxxzqfyo6mtPD2oaWLpQJmnf9A+AtLIK7lKEikSOgKlD8yGPFvXgVOwP8pdeBHsoBOBLlKpMJrTWy0zqGz5PhXtyJqSODpMKvPbWGs/RJWAC/ez2So2up7W1sWQwhdF9v/4XRsTW0FOzdlboNHLYOLeI/XdL4vkYf+plXqPWtoIT/S5ZlKEK+6+1CJuI89rlbRI1VJAcaJyqzIQuwwGOAGrVrm5G0rCJpkhtDWjwhXx1CgySWvYJ0YbvYnFdFtHqhH1HF1SlWf/2h6+or8DikEPfpCwAY1aPA+KuaI+srcngf7whyc7DbvhX6Rp9DQMZW16yF87uCNjrGVei/mz5vlFfW8fKHcXzAl3SFGYyW1od+RsjIistkjxHGI0xalKMw3wQU2RIhN5EUdZKCR0ZCx11XZAVIk5J+aaxYdphC9J7T76QWJJotf1BKOpXnp35qYoDkaI/0KHdY2d7fVMGCrfVju9UJOLEjsR7XaWBLFK+s/i3OgOPLSp9YbNeWqcyfQQ="
  secret_access_key: "ezYLpTeEYcmA4XClTZwCN7IX5pgoUTW+t23fX65hvNDfmJDGyzN21zFtieyuSpvNGSnDvID0TrAryFv6/s0j055fuFjDVhyxuCU/hF0b+OOmCqPSVV0HTz4vT34RSp81DCYqYd4mIibJqCaBx9gBiMuBOkYHFQEBCCh8n8hWakfgeojuCtVvPJgwWS/iwe+561Za9m+fPZdL2ArjgjsGW0t98iOgHw5oqD3kdLmYYRBvShL7IizwTAOh6eAa5lOeDp0OKpoDBYJJglZvmADc7X6raBOuc2bjVJN+3LWJqJ4NihO78SBJh7f1dU0HkxjEwb/hmzC4zfTwQwA+SRpB6hYzvkvs42C2OgTZ4wrtPU3A72eeq5dt1hAPEnRiuyMrqrvhz1MwPtj4SCYH2xuAFlB7BifUyl4BfgEsdyzyLm9vV3QR9ZftORbaXk8gbmoKUIkVoUQjBFCsRGwzLjZNzW7L2Is2DzA8qfynE3Y2A9iNi1vBQPC4urC0wE888fI7Bgo+Zu8UoXfRpr3GkNDu5s2kgFHS+PKMjVYuuoHnxVN2zBYp1j3xroy+/bID5samsRDi3lh8HGigi/ZT89ZbqeySPEjSmdEnEgzQXAfMSzIDGU2qDWLsWbLz2nn4RGT5ZnMzvu/iovVRqMlFXTGyTFbNwOs8ZjqBoCjYVFxDVCU="
  bucket: "shadowpact"
  skip_cleanup: "true"
  bundle_type: "jar"
  key: "*.jar"
  debug: "true"
  application: "node-app"
  region: "us-west-2"
  deployment_group: "springappGroup"
  local-dir: "build/libs"
  on:
    branch: "master"
