#addons:
# artifacts: 
#  paths:
#   - build/libs
#  debug: true
#env:
# global:
#  - "ARTIFACTS_AWS_REGION=eu-west-1"
#  - "ARTIFACTS_S3_BUCKET=shadowpact"
#  - "ARTIFACTS_KEY=CbA+UQ8rQfSj0AHu7iv2dm6KiqAu70v4mUqKn5vGIOONHcVZVCw6qsmGIQAIyz7CQvfFN5THd/ZWlEBKRZr4HxJtl7c+MSbPnDD4PTgeV/p1ZUlulbWNxWIHDZI9xuAHpZDchQJ4d5R62j2ASZkUiIj8ctDJLeJYh8JtmcnZ6td939WoYjWoRENPi+xgS3gSJrcY8w9Bq9SwY6xVHcSxOEaQwAyz6Ge7gX2liRIcfLLUNnpqAzg+A3LlfD6L9qeYzaqOdTBjcmsBL1OzxwshylLKd7jPp5uDC0h3NCNaZ/WatPjNE6QeTtWvxqMbRBhurb/pOnWHNrM3WmZU3d9lFr4r4Qwq/aoiwA9xOM0oZ/1FfdlDXlpf5rcqyecllPNsOeGzDegfifwxdIkVrjyJf41m3AXLpmf2jExjJwIGsVFa+EKE40YxuBxU0k0h7OkVx+JrXd80VQKzvYi7SJWGdmY+ZmaT6oRBKmOqfSk/Ti+7yZi0/THBxshFVrgl7cEZAcvwtvg51dqpHVIccG8f2wtZqs0x5YBLbOknUsw4LMJThqWRZB2bxJxl5kLA5p6HdQH/QWi+6WFguQBk75/+f6MZvR9E7ZYzhEnxPgSTgU1E0HnWvYQe9Obyp+DPVkqXY9vNJmkkp3oU0rxgb1GaVaHDVwlqkt+VWD0Bd9pDxt8="
#  - "ARTIFACTS_SECRET=X1kb4aWuGolq9AOQ/SeBqXa0vKC/LAF/6vjYdlTPo/5mCOkLmF8TdcjW8lVAl38OjuawES7j6GZU3CcEYEFOeem8K/EyDqyoiuTimdW1jrgdUcw683gOUrEVnkSq+ovdbUvAlkOyv4+8CrlhmB726aBUcIWulSEc3q4vrHK5GUbWJqcNQKOHciGjewTuDtOnY5LOgOVksd1obDCjwDcp0Z0KAXgeq7dl/xDDigeX9y3Tr4GvfVJjvD9uOZrK3UtAxV4wT1+QcgpzJQIW0f5qzv/S5FzBrSeb1Sl2u7N+zJDgtbr5vDF5KFsA1TkSj/hyYFPbMDUMwh7UCaa4OAXkeKuZx9jdmBP9tyUrSUYAQoH/Bs0lFlo52AnBKHF5I/h7oOYZLdwJH3JhUrTjSxGjh2ocAEDBMhNLOXNatR7oS60O1jaN+x7luWolGbX0nhRbr48ucmPV9jh10XPuD10X3ccSsYp/Gt/AxTjOk6pOfhQOa6PD3sAbGNPNGvRUbJMEy4NIiU6mYoHRxKRhEiHKPOJgqnqlY+b2RGakWGNZowI850HDNXXfbKsPGiObgiNF8TeatYOlkAir1FvBOJOUXVAbo9XngNORzEcOEKojDPAizJwuw1clHvVZ+6/8LkyGNgXDA2Hc0NnTmqcwFgrNT1ub68pJqKLdsst9fP1qaLQ="

language: java
jdk:
  - oraclejdk8
before_script:
  - "gem install travis-artifacts"
#after_failure: # this will of course run only on failure
#  - "travis-artifacts upload --path debug/debug.log"
#after_success: # and this only on success
#  - "travis-artifacts upload --target-path build/libs/*.jar"

#artifacts upload \
#  --key CbA+UQ8rQfSj0AHu7iv2dm6KiqAu70v4mUqKn5vGIOONHcVZVCw6qsmGIQAIyz7CQvfFN5THd/ZWlEBKRZr4HxJtl7c+MSbPnDD4PTgeV/p1ZUlulbWNxWIHDZI9xuAHpZDchQJ4d5R62j2ASZkUiIj8ctDJLeJYh8JtmcnZ6td939WoYjWoRENPi+xgS3gSJrcY8w9Bq9SwY6xVHcSxOEaQwAyz6Ge7gX2liRIcfLLUNnpqAzg+A3LlfD6L9qeYzaqOdTBjcmsBL1OzxwshylLKd7jPp5uDC0h3NCNaZ/WatPjNE6QeTtWvxqMbRBhurb/pOnWHNrM3WmZU3d9lFr4r4Qwq/aoiwA9xOM0oZ/1FfdlDXlpf5rcqyecllPNsOeGzDegfifwxdIkVrjyJf41m3AXLpmf2jExjJwIGsVFa+EKE40YxuBxU0k0h7OkVx+JrXd80VQKzvYi7SJWGdmY+ZmaT6oRBKmOqfSk/Ti+7yZi0/THBxshFVrgl7cEZAcvwtvg51dqpHVIccG8f2wtZqs0x5YBLbOknUsw4LMJThqWRZB2bxJxl5kLA5p6HdQH/QWi+6WFguQBk75/+f6MZvR9E7ZYzhEnxPgSTgU1E0HnWvYQe9Obyp+DPVkqXY9vNJmkkp3oU0rxgb1GaVaHDVwlqkt+VWD0Bd9pDxt8= \
#  --secret X1kb4aWuGolq9AOQ/SeBqXa0vKC/LAF/6vjYdlTPo/5mCOkLmF8TdcjW8lVAl38OjuawES7j6GZU3CcEYEFOeem8K/EyDqyoiuTimdW1jrgdUcw683gOUrEVnkSq+ovdbUvAlkOyv4+8CrlhmB726aBUcIWulSEc3q4vrHK5GUbWJqcNQKOHciGjewTuDtOnY5LOgOVksd1obDCjwDcp0Z0KAXgeq7dl/xDDigeX9y3Tr4GvfVJjvD9uOZrK3UtAxV4wT1+QcgpzJQIW0f5qzv/S5FzBrSeb1Sl2u7N+zJDgtbr5vDF5KFsA1TkSj/hyYFPbMDUMwh7UCaa4OAXkeKuZx9jdmBP9tyUrSUYAQoH/Bs0lFlo52AnBKHF5I/h7oOYZLdwJH3JhUrTjSxGjh2ocAEDBMhNLOXNatR7oS60O1jaN+x7luWolGbX0nhRbr48ucmPV9jh10XPuD10X3ccSsYp/Gt/AxTjOk6pOfhQOa6PD3sAbGNPNGvRUbJMEy4NIiU6mYoHRxKRhEiHKPOJgqnqlY+b2RGakWGNZowI850HDNXXfbKsPGiObgiNF8TeatYOlkAir1FvBOJOUXVAbo9XngNORzEcOEKojDPAizJwuw1clHvVZ+6/8LkyGNgXDA2Hc0NnTmqcwFgrNT1ub68pJqKLdsst9fP1qaLQ= \
#  --bucket shadowpact \
#  --region eu-west-1
#  $(git ls-files -o)  
  
  
deploy:
  provider: s3
  access_key_id: "CbA+UQ8rQfSj0AHu7iv2dm6KiqAu70v4mUqKn5vGIOONHcVZVCw6qsmGIQAIyz7CQvfFN5THd/ZWlEBKRZr4HxJtl7c+MSbPnDD4PTgeV/p1ZUlulbWNxWIHDZI9xuAHpZDchQJ4d5R62j2ASZkUiIj8ctDJLeJYh8JtmcnZ6td939WoYjWoRENPi+xgS3gSJrcY8w9Bq9SwY6xVHcSxOEaQwAyz6Ge7gX2liRIcfLLUNnpqAzg+A3LlfD6L9qeYzaqOdTBjcmsBL1OzxwshylLKd7jPp5uDC0h3NCNaZ/WatPjNE6QeTtWvxqMbRBhurb/pOnWHNrM3WmZU3d9lFr4r4Qwq/aoiwA9xOM0oZ/1FfdlDXlpf5rcqyecllPNsOeGzDegfifwxdIkVrjyJf41m3AXLpmf2jExjJwIGsVFa+EKE40YxuBxU0k0h7OkVx+JrXd80VQKzvYi7SJWGdmY+ZmaT6oRBKmOqfSk/Ti+7yZi0/THBxshFVrgl7cEZAcvwtvg51dqpHVIccG8f2wtZqs0x5YBLbOknUsw4LMJThqWRZB2bxJxl5kLA5p6HdQH/QWi+6WFguQBk75/+f6MZvR9E7ZYzhEnxPgSTgU1E0HnWvYQe9Obyp+DPVkqXY9vNJmkkp3oU0rxgb1GaVaHDVwlqkt+VWD0Bd9pDxt8="
  secret_access_key: "X1kb4aWuGolq9AOQ/SeBqXa0vKC/LAF/6vjYdlTPo/5mCOkLmF8TdcjW8lVAl38OjuawES7j6GZU3CcEYEFOeem8K/EyDqyoiuTimdW1jrgdUcw683gOUrEVnkSq+ovdbUvAlkOyv4+8CrlhmB726aBUcIWulSEc3q4vrHK5GUbWJqcNQKOHciGjewTuDtOnY5LOgOVksd1obDCjwDcp0Z0KAXgeq7dl/xDDigeX9y3Tr4GvfVJjvD9uOZrK3UtAxV4wT1+QcgpzJQIW0f5qzv/S5FzBrSeb1Sl2u7N+zJDgtbr5vDF5KFsA1TkSj/hyYFPbMDUMwh7UCaa4OAXkeKuZx9jdmBP9tyUrSUYAQoH/Bs0lFlo52AnBKHF5I/h7oOYZLdwJH3JhUrTjSxGjh2ocAEDBMhNLOXNatR7oS60O1jaN+x7luWolGbX0nhRbr48ucmPV9jh10XPuD10X3ccSsYp/Gt/AxTjOk6pOfhQOa6PD3sAbGNPNGvRUbJMEy4NIiU6mYoHRxKRhEiHKPOJgqnqlY+b2RGakWGNZowI850HDNXXfbKsPGiObgiNF8TeatYOlkAir1FvBOJOUXVAbo9XngNORzEcOEKojDPAizJwuw1clHvVZ+6/8LkyGNgXDA2Hc0NnTmqcwFgrNT1ub68pJqKLdsst9fP1qaLQ="
  bucket: "shadowpact"
  skip_cleanup: true
  endpoint: "s3-website-eu-west-1.amazonaws.com"
  region: "eu-west-1"
  debug: true
  upload-dir: artifacts
  local-dir: build/libs
  
